# Generated by Django 5.1 on 2024-08-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtrip.trip'),
        ),
    ]
